Add CSS for contact validation
dfizzkruah93/Pofolio-Project pull request #9
Opened 2022-03-09 19:21 UTC by dfizzkruah93

- Update Index file

- Add Js file for form validation

2022-03-09 19:36 UTC, mmsesay requested changes
Hi @dfizzkruah93, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-09 19:36 UTC, mmsesay commented on js/script.js
> +});
- [ ] The email verification is not working as expected. I inputted an uppercase email then the form got submitted without any errors. Please work on this validation to check if the email is in lower case.

See test screenshot

Filling the form | After Submitting |
:------------------:|:----------------------:|
![a1](https://user-images.githubusercontent.com/39523312/157518507-ed2b7197-6539-480e-9116-013e580263a6.png)| ![a2](https://user-images.githubusercontent.com/39523312/157518521-14fc4ed5-be32-4071-8839-836a6e60ca75.png)

2022-03-10 07:16 UTC, Meltrust approved these changes
Hi @dfizzkruah93,


## Wow, you did it 🎉
![image](https://user-images.githubusercontent.com/57421823/157608685-189207db-ad36-407e-ba63-070f64f00755.png)

![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for correcting the form validation, as requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-10 08:07 UTC, dfizzkruah93 commented
@Meltrust. Thanks for the approval.

2022-03-10 08:07 UTC, merged